/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingSol from "./Voting.sol";
export type { votingSol };
export type { BALToken } from "./BALToken";
export type { CandidateNFT } from "./CandidateNFT";
