/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBALToken,
  IBALTokenInterface,
} from "../../../contracts/Voting.sol/IBALToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBALToken__factory {
  static readonly abi = _abi;
  static createInterface(): IBALTokenInterface {
    return new Interface(_abi) as IBALTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBALToken {
    return new Contract(address, _abi, runner) as unknown as IBALToken;
  }
}
