/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBALToken } from "./IBALToken";
export type { ICandidateNFT } from "./ICandidateNFT";
export type { Voting } from "./Voting";
