/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as votingSol from "./Voting.sol";
export { BALToken__factory } from "./BALToken__factory";
export { CandidateNFT__factory } from "./CandidateNFT__factory";
